# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tbergkul <tbergkul@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/15 14:53:29 by tbergkul          #+#    #+#              #
#    Updated: 2019/10/15 17:58:13 by tbergkul         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

FILE = ft_display_file.c

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(FILE)

clean:
	/bin/rm -f *.o

fclean:
	/bin/rm -f $(NAME)
